# Generated by Django 6.0.4 on 2026-04-24 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('evidence_count', models.IntegerField(default=0)),
                ('ai_scans', models.IntegerField(default=0)),
                ('threats_detected', models.IntegerField(default=0)),
                ('fraud_prevented_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('blockchain_anchors', models.IntegerField(default=0)),
                ('compliance_score', models.FloatField(default=0.0)),
                ('active_users', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('iot_pushes', models.IntegerField(default=0)),
                ('avg_trust_score', models.FloatField(default=0.0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='tap_org.organization')),
            ],
            options={
                'db_table': 'tap_executive_kpis',
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
