# Generated by Django 4.2.7 on 2026-04-21 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('UPLOAD', 'Upload'), ('MODIFY', 'Modify'), ('VERIFY', 'Verify'), ('STORE', 'Store'), ('FLAG', 'Flag'), ('NOTE', 'Note')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('event_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sequence_number', models.PositiveIntegerField(default=0)),
                ('blockchain_anchored', models.BooleanField(default=False)),
                ('blockchain_tx', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tap_evidence.evidence')),
                ('previous_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_events', to='tap_events.event')),
            ],
            options={
                'db_table': 'tap_events',
                'ordering': ['timestamp', 'sequence_number'],
            },
        ),
    ]
