# Generated by Django 5.2.13 on 2026-05-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('MODIFY', 'Modify'), ('VERIFY', 'Verify'), ('STORE', 'Store'), ('FLAG', 'Flag'), ('NOTE', 'Note'), ('EXPIRE_SET', 'Expiry Set'), ('EXPIRED', 'Expired')], max_length=20),
        ),
    ]
