# Generated by Django 6.0.4 on 2026-04-23 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_evidence', '0002_evidence_is_latest_version_evidence_parent_evidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('text_similarity', models.FloatField(default=1.0)),
                ('words_added', models.IntegerField(default=0)),
                ('words_removed', models.IntegerField(default=0)),
                ('chars_changed', models.IntegerField(default=0)),
                ('file_size_delta', models.BigIntegerField(default=0)),
                ('hash_changed', models.BooleanField(default=False)),
                ('change_type', models.CharField(choices=[('MINOR', 'Minor Edit'), ('MAJOR', 'Major Revision'), ('FORGED', 'Suspected Forgery'), ('CRITICAL', 'Critical Alteration')], default='MINOR', max_length=20)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('fraud_signals', models.JSONField(default=list)),
                ('diff_summary', models.TextField(blank=True)),
                ('compared_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_target', to='tap_evidence.evidence')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_versions', to='tap_evidence.evidence')),
            ],
            options={
                'db_table': 'tap_doc_versions',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
