# Generated by Django 5.2.13 on 2026-05-02 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap_evidence', '0003_evidence_expired_at_evidence_expires_at_and_more'),
        ('tap_evolution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Moderate Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=10)),
                ('features', models.JSONField(default=dict)),
                ('patterns', models.JSONField(default=list)),
                ('version_count', models.IntegerField(default=0)),
                ('comparison_count', models.IntegerField(default=0)),
                ('chain_span_days', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_analyses', to='tap_evidence.evidence')),
            ],
            options={
                'db_table': 'tap_evolution_ai',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
