# Generated by Django 6.0.4 on 2026-04-24 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_evidence', '0002_evidence_is_latest_version_evidence_parent_evidence_and_more'),
        ('tap_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case', models.CharField(choices=[('DOCUMENT_AUTH', 'Document Authenticity'), ('CREDENTIAL', 'Credential Verification'), ('MEDICAL_RECORD', 'Medical Record'), ('LEGAL_CERT', 'Legal Certificate'), ('EDUCATION', 'Educational Credential'), ('CORPORATE', 'Corporate Compliance')], default='DOCUMENT_AUTH', max_length=20)),
                ('proof_id', models.CharField(max_length=64, unique=True)),
                ('commitment', models.CharField(max_length=128)),
                ('nullifier', models.CharField(max_length=64)),
                ('public_inputs', models.JSONField(default=dict)),
                ('proof_circuit', models.CharField(default='groth16-sha256', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('verification_url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zkp_created', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zkp_proofs', to='tap_evidence.evidence')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_org.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zkp_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_zkp_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
