# Generated by Django 5.2.13 on 2026-05-02 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap_evidence', '0003_evidence_expired_at_evidence_expires_at_and_more'),
        ('tap_zkp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='zkpverification',
            name='use_case',
            field=models.CharField(choices=[('DOCUMENT_AUTH', 'Document Authenticity'), ('CREDENTIAL', 'Credential Verification'), ('MEDICAL_RECORD', 'Medical Record'), ('LEGAL_CERT', 'Legal Certificate'), ('EDUCATION', 'Educational Credential'), ('CORPORATE', 'Corporate Compliance'), ('RESUME', 'Resume Verification'), ('SKILL_CERT', 'Skill Certification')], default='DOCUMENT_AUTH', max_length=20),
        ),
        migrations.CreateModel(
            name='TrustedIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer_type', models.CharField(choices=[('UNIVERSITY', 'University/College'), ('CERTIFICATION', 'Certification Body'), ('EMPLOYER', 'Employer'), ('GOVERNMENT', 'Government Agency'), ('PROFESSIONAL', 'Professional Body')], default='UNIVERSITY', max_length=20)),
                ('trust_level', models.CharField(choices=[('VERIFIED', 'Verified'), ('TRUSTED', 'Trusted'), ('PENDING', 'Pending Verification'), ('REVOKED', 'Revoked')], default='PENDING', max_length=10)),
                ('issuer_hash', models.CharField(max_length=64, unique=True)),
                ('public_key', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_trusted_issuers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResumeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('DEGREE', 'Academic Degree'), ('DIPLOMA', 'Diploma'), ('CERTIFICATION', 'Professional Certification'), ('SKILL', 'Verified Skill'), ('EMPLOYMENT', 'Employment History'), ('LICENSE', 'Professional License')], default='DEGREE', max_length=20)),
                ('claim_title', models.CharField(max_length=255)),
                ('claim_detail', models.TextField(blank=True)),
                ('issuer_name', models.CharField(blank=True, max_length=255)),
                ('document_hash', models.CharField(blank=True, max_length=64)),
                ('commitment', models.CharField(blank=True, max_length=128)),
                ('commitment_salt', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_credentials', to='tap_evidence.evidence')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_credentials', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_credentials', to=settings.AUTH_USER_MODEL)),
                ('zkp_proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='tap_zkp.zkpverification')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_zkp.trustedissuer')),
            ],
            options={
                'db_table': 'tap_resume_credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Credential Submitted'), ('VERIFY', 'Verification Attempt'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('EXPIRE', 'Expired'), ('REVOKE', 'Revoked')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='tap_zkp.resumecredential')),
                ('zkp_proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='tap_zkp.zkpverification')),
            ],
            options={
                'db_table': 'tap_verification_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
