# Generated by Django 6.0.4 on 2026-04-25 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('twin_type', models.CharField(choices=[('NETWORK', 'Network Infrastructure'), ('CLOUD', 'Cloud Environment'), ('INDUSTRIAL', 'Industrial ICS/SCADA'), ('HOSPITAL', 'Hospital Systems'), ('SMART_CITY', 'Smart City'), ('AIRPORT', 'Airport Systems'), ('MILITARY', 'Defense Network')], max_length=15)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Simulation Running'), ('PAUSED', 'Paused'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='IDLE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topology', models.JSONField(default=dict)),
                ('assets', models.JSONField(default=list)),
                ('vulnerabilities', models.JSONField(default=list)),
                ('total_simulations', models.IntegerField(default=0)),
                ('last_simulation', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_org.organization')),
            ],
            options={
                'db_table': 'tap_digital_twins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwinSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_scenario', models.CharField(choices=[('RANSOMWARE', 'Ransomware Attack'), ('DDoS', 'DDoS Flood'), ('APT_LATERAL', 'APT Lateral Movement'), ('SUPPLY_CHAIN', 'Supply Chain Compromise'), ('INSIDER', 'Insider Data Theft'), ('ZERO_DAY', 'Zero-Day Exploit'), ('PHISHING', 'Spear Phishing'), ('IOT_PIVOT', 'IoT Pivot Attack')], max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('detection_time', models.IntegerField(default=0)),
                ('was_detected', models.BooleanField(null=True)),
                ('ai_response_score', models.FloatField(default=0.0)),
                ('kill_chain_steps', models.JSONField(default=list)),
                ('affected_assets', models.JSONField(default=list)),
                ('evidence_generated', models.JSONField(default=list)),
                ('report_data', models.JSONField(default=dict)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='tap_dtwin.digitaltwin')),
            ],
            options={
                'db_table': 'tap_twin_simulations',
                'ordering': ['-started_at'],
            },
        ),
    ]
