# Generated by Django 6.0.4 on 2026-04-25 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_type', models.CharField(choices=[('PROTOCOL_UPGRADE', 'Protocol Upgrade'), ('STANDARD_CHANGE', 'Verification Standard'), ('NODE_ADMISSION', 'Node Admission'), ('PARAMETER_CHANGE', 'Parameter Change'), ('EMERGENCY', 'Emergency Action'), ('BUDGET', 'Treasury Budget'), ('RULE', 'Rule Amendment')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('technical_spec', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active Voting'), ('PASSED', 'Passed'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed')], default='DRAFT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voting_start', models.DateTimeField(blank=True, null=True)),
                ('voting_end', models.DateTimeField(blank=True, null=True)),
                ('votes_for', models.IntegerField(default=0)),
                ('votes_against', models.IntegerField(default=0)),
                ('votes_abstain', models.IntegerField(default=0)),
                ('quorum_required', models.IntegerField(default=51)),
                ('pass_threshold', models.IntegerField(default=67)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('on_chain_hash', models.CharField(blank=True, max_length=64)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_dao_proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DAOVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('FOR', 'For'), ('AGAINST', 'Against'), ('ABSTAIN', 'Abstain')], max_length=10)),
                ('weight', models.FloatField(default=1.0)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('rationale', models.TextField(blank=True)),
                ('on_chain_tx', models.CharField(blank=True, max_length=100)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tap_dao.governanceproposal')),
            ],
            options={
                'db_table': 'tap_dao_votes',
                'unique_together': {('proposal', 'voter')},
            },
        ),
    ]
