# Generated by Django 6.0.4 on 2026-04-24 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_evidence', '0002_evidence_is_latest_version_evidence_parent_evidence_and_more'),
        ('tap_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('UPLOAD', 'Evidence Upload'), ('AI_SCAN', 'AI Scan'), ('BLOCKCHAIN', 'Blockchain TX'), ('ALERT', 'Alert Triggered'), ('LOGIN', 'User Login'), ('IOT_PUSH', 'IoT Data Push')], max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('icon', models.CharField(default='●', max_length=10)),
                ('color', models.CharField(default='#00d4ff', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_org.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_live_feed',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SOCAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('AI_ANOMALY', 'AI Anomaly Detected'), ('REPLAY_ATTACK', 'Replay Attack'), ('TIMESTAMP_TAMPER', 'Timestamp Tampering'), ('CHAIN_BREAK', 'Chain Integrity Break'), ('IOT_INTRUSION', 'IoT Intrusion'), ('MASS_UPLOAD', 'Mass Upload Spike'), ('INSIDER_THREAT', 'Insider Threat Signal'), ('ZKP_FAIL', 'ZKP Verification Failed'), ('BLOCKCHAIN_FAIL', 'Blockchain Anchor Failed'), ('GEO_ANOMALY', 'Geolocation Anomaly')], max_length=30)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('geo_country', models.CharField(blank=True, max_length=80)),
                ('geo_city', models.CharField(blank=True, max_length=80)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_lon', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_evidence.evidence')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soc_alerts', to='tap_org.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_soc_alerts',
                'ordering': ['-detected_at'],
            },
        ),
    ]
