# Generated by Django 6.0.4 on 2026-04-24 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise'), ('GOVERNMENT', 'Government')], max_length=50, unique=True)),
                ('price_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_year', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_users', models.IntegerField(default=5)),
                ('max_evidence_gb', models.FloatField(default=1.0)),
                ('api_calls_day', models.IntegerField(default=100)),
                ('ai_scans_month', models.IntegerField(default=50)),
                ('blockchain_anchors', models.IntegerField(default=10)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tap_subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIALING', 'Trialing'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled')], default='TRIALING', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('stripe_sub_id', models.CharField(blank=True, max_length=100)),
                ('api_calls_used', models.IntegerField(default=0)),
                ('evidence_gb_used', models.FloatField(default=0.0)),
                ('ai_scans_used', models.IntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tap_org.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tap_billing.subscriptionplan')),
            ],
            options={
                'db_table': 'tap_org_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('API_CALL', 'API Call'), ('EVIDENCE_UPLOAD', 'Upload'), ('AI_SCAN', 'AI Scan'), ('BLOCKCHAIN_TX', 'Blockchain TX'), ('REPORT_GEN', 'Report')], max_length=20)),
                ('quantity', models.FloatField(default=1.0)),
                ('cost_units', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='tap_org.organization')),
            ],
            options={
                'db_table': 'tap_usage_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
