# Generated by Django 6.0.4 on 2026-04-24 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_evidence', '0002_evidence_is_latest_version_evidence_parent_evidence_and_more'),
        ('tap_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('device_type', models.CharField(choices=[('CCTV', 'CCTV Camera'), ('SENSOR', 'Smart Sensor'), ('BIOMETRIC', 'Biometric System'), ('ACCESS_CTRL', 'Access Control'), ('INDUSTRIAL', 'Industrial IoT'), ('NETWORK', 'Network Device'), ('MOBILE_UNIT', 'Mobile Unit'), ('DRONE', 'Drone / UAV'), ('WEARABLE', 'Wearable Device')], max_length=20)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('api_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ALERT', 'In Alert'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=15)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('total_pushes', models.BigIntegerField(default=0)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_lon', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_devices', to='tap_org.organization')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_iot_devices',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='IoTDataPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload_size', models.IntegerField(default=0)),
                ('payload_type', models.CharField(default='json', max_length=50)),
                ('verdict', models.CharField(choices=[('CLEAN', 'Clean'), ('SUSPICIOUS', 'Suspicious'), ('ANOMALOUS', 'Anomalous'), ('PENDING', 'Pending')], default='PENDING', max_length=15)),
                ('ai_score', models.FloatField(default=0.0)),
                ('raw_preview', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_evidence.evidence')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_pushes', to='tap_iot.iotdevice')),
            ],
            options={
                'db_table': 'tap_iot_pushes',
                'ordering': ['-received_at'],
            },
        ),
    ]
