# Generated by Django 4.2.7 on 2026-04-21 20:20

import apps.evidence.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apps.evidence.models.evidence_upload_path)),
                ('filename_original', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged'), ('STORED', 'Stored'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20)),
                ('trust_score', models.IntegerField(default=100)),
                ('ipfs_cid', models.CharField(blank=True, help_text='IPFS CID — populated in Phase 2', max_length=255)),
                ('blockchain_tx', models.CharField(blank=True, help_text='Blockchain TX — populated in Phase 2', max_length=255)),
                ('case_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_evidence',
                'ordering': ['-created_at'],
            },
        ),
    ]
