# Generated by Django 4.2.7 on 2026-04-22 07:53

import apps.evidence.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tap_evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='is_latest_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='parent_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='tap_evidence.evidence'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.evidence.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='ipfs_cid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
