# Generated by Django 5.2.13 on 2026-05-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap_evidence', '0002_evidence_is_latest_version_evidence_parent_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='expiry_condition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='evidence',
            name='expiry_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidence',
            name='expiry_type',
            field=models.CharField(choices=[('NONE', 'No Expiry'), ('TIMED', 'Time-Based'), ('EVENT', 'Event-Based')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='evidence',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
