# Generated by Django 6.0.4 on 2026-04-25 02:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threat_class', models.CharField(choices=[('MALWARE', 'Malware'), ('RANSOMWARE', 'Ransomware'), ('APT', 'APT'), ('PHISHING', 'Phishing'), ('INSIDER', 'Insider Threat'), ('ZERO_DAY', 'Zero-Day'), ('SUPPLY_CHAIN', 'Supply Chain'), ('DEEPFAKE', 'Deepfake Document'), ('IOT_ATTACK', 'IoT Attack')], max_length=20)),
                ('ioc_type', models.CharField(max_length=30)),
                ('ioc_value_hash', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('confidence', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Verified'), (5, 'Confirmed Critical')], default=2)),
                ('severity', models.CharField(default='MEDIUM', max_length=10)),
                ('contributed_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('global_matches', models.IntegerField(default=0)),
                ('verified_by_nodes', models.IntegerField(default=0)),
                ('stix_json', models.JSONField(default=dict)),
                ('ttps', models.JSONField(default=list)),
                ('mitre_tactics', models.JSONField(default=list)),
                ('contributed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_org.organization')),
            ],
            options={
                'db_table': 'tap_threat_signatures',
                'ordering': ['-contributed_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_source', models.CharField(choices=[('CONSORTIUM', 'Global Consortium'), ('CERT', 'National CERT'), ('INTERPOL', 'INTERPOL'), ('MITRE', 'MITRE ATT&CK'), ('ISA', 'ISAC'), ('TAP_AI', 'TAP-DEV AI')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=10)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('affected_sectors', models.JSONField(default=list)),
                ('affected_countries', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('signatures', models.ManyToManyField(blank=True, to='tap_tshare.threatsignature')),
            ],
            options={
                'db_table': 'tap_threat_feeds',
                'ordering': ['-published_at'],
            },
        ),
    ]
