# Generated by Django 6.0.4 on 2026-04-25 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_evidence', '0002_evidence_is_latest_version_evidence_parent_evidence_and_more'),
        ('tap_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('node_type', models.CharField(choices=[('GOVERNMENT', 'Government'), ('LAW_ENFORCEMENT', 'Law Enforcement'), ('COURT', 'Court System'), ('ENTERPRISE', 'Enterprise'), ('UNIVERSITY', 'University'), ('HOSPITAL', 'Hospital'), ('MILITARY', 'Military'), ('INTERPOL', 'Interpol')], max_length=20)),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OFFLINE', 'Offline'), ('SYNCING', 'Syncing'), ('COMPROMISED', 'Compromised')], default='ACTIVE', max_length=15)),
                ('blockchain', models.CharField(choices=[('ETHEREUM', 'Ethereum'), ('POLYGON', 'Polygon'), ('HYPERLEDGER', 'Hyperledger Fabric'), ('SOLANA', 'Solana'), ('AVALANCHE', 'Avalanche'), ('COSMOS', 'Cosmos IBC')], default='ETHEREUM', max_length=20)),
                ('node_address', models.CharField(max_length=200)),
                ('public_key', models.TextField()),
                ('did_identifier', models.CharField(blank=True, max_length=200)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_lon', models.FloatField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('evidence_count', models.BigIntegerField(default=0)),
                ('trust_score', models.FloatField(default=100.0)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'tap_forensic_nodes',
                'ordering': ['country_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrossChainTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('source_chain', models.CharField(max_length=20)),
                ('target_chain', models.CharField(max_length=20)),
                ('bridge_protocol', models.CharField(default='IBC', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BRIDGING', 'Bridging'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REVERTED', 'Reverted')], default='PENDING', max_length=15)),
                ('source_tx_hash', models.CharField(blank=True, max_length=100)),
                ('target_tx_hash', models.CharField(blank=True, max_length=100)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('attestation', models.TextField(blank=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_chain', to='tap_evidence.evidence')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound', to='tap_gnet.forensicnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound', to='tap_gnet.forensicnode')),
            ],
            options={
                'db_table': 'tap_cross_chain_transfers',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkConsortiumMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('verification_level', models.IntegerField(default=1)),
                ('dao_votes_cast', models.IntegerField(default=0)),
                ('reputation_score', models.FloatField(default=1.0)),
                ('forensic_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tap_gnet.forensicnode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tap_org.organization')),
            ],
            options={
                'db_table': 'tap_consortium_members',
            },
        ),
    ]
