# Generated by Django 4.2.7 on 2026-04-21 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_events', '0001_initial'),
        ('tap_evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('INVALID_SEQUENCE', 'Invalid Event Sequence'), ('BACKWARD_TIMESTAMP', 'Backward Timestamp'), ('MISSING_STEP', 'Missing Logical Step'), ('LARGE_GAP', 'Large Time Gap'), ('DUPLICATE_EVENT', 'Duplicate Event Type'), ('HASH_MISMATCH', 'Chain Hash Mismatch'), ('PREMATURE_VERIFY', 'Premature Verification'), ('ORPHAN_MODIFY', 'Orphan Modification')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='tap_evidence.evidence')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_events.event')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_anomalies',
                'ordering': ['-detected_at'],
            },
        ),
    ]
