# Generated by Django 6.0.4 on 2026-04-25 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=32, unique=True)),
                ('client_secret_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=15)),
                ('redirect_uris', models.JSONField(default=list)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_calls_total', models.BigIntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_org.organization')),
            ],
            options={
                'db_table': 'tap_developer_apps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePlugin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('plugin_type', models.CharField(choices=[('CONNECTOR', 'Data Connector'), ('ANALYZER', 'Analysis Plugin'), ('REPORTER', 'Report Template'), ('VISUALIZER', 'Visualization'), ('INTEGRATION', '3rd Party Integration'), ('WORKFLOW', 'Workflow Automation')], max_length=15)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DEPRECATED', 'Deprecated')], default='PENDING', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('installs', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('api_endpoint', models.URLField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('permissions_required', models.JSONField(default=list)),
                ('compatible_phases', models.JSONField(default=list)),
                ('changelog', models.TextField(blank=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_marketplace_plugins',
                'ordering': ['-installs'],
            },
        ),
    ]
