# Generated by Django 6.0.4 on 2026-04-24 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GDPR', 'GDPR'), ('HIPAA', 'HIPAA'), ('ISO27001', 'ISO 27001'), ('SOC2', 'SOC 2'), ('PCI_DSS', 'PCI DSS'), ('NIST', 'NIST CSF'), ('ISO27701', 'ISO 27701'), ('CCPA', 'CCPA')], max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('version', models.CharField(blank=True, max_length=20)),
                ('controls', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tap_compliance_frameworks',
            },
        ),
        migrations.CreateModel(
            name='ComplianceAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REMEDIATION', 'Remediation')], default='IN_PROGRESS', max_length=15)),
                ('overall_score', models.FloatField(default=0.0)),
                ('findings', models.JSONField(default=list)),
                ('remediation_plan', models.TextField(blank=True)),
                ('next_assessment', models.DateField(blank=True, null=True)),
                ('cert_issued', models.BooleanField(default=False)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assessments', to='tap_org.organization')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tap_compliance.complianceframework')),
            ],
            options={
                'db_table': 'tap_compliance_assessments',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=30)),
                ('control_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('PARTIAL', 'Partial'), ('NON_COMPLIANT', 'Non-Compliant'), ('NA', 'N/A')], default='NON_COMPLIANT', max_length=15)),
                ('score', models.FloatField(default=0.0)),
                ('evidence_refs', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='tap_compliance.complianceassessment')),
            ],
            options={
                'db_table': 'tap_compliance_controls',
            },
        ),
    ]
