# Generated by Django 4.2.7 on 2026-04-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tap_evidence', '0002_evidence_is_latest_version_evidence_parent_evidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPFSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100)),
                ('gateway_url', models.URLField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipfs_records', to='tap_evidence.evidence')),
            ],
            options={
                'db_table': 'tap_ipfs_records',
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(default=0)),
                ('network', models.CharField(choices=[('ETHEREUM_SIM', 'Ethereum (Simulation)'), ('HYPERLEDGER_SIM', 'Hyperledger (Simulation)'), ('ETHEREUM', 'Ethereum Mainnet'), ('POLYGON', 'Polygon')], default='ETHEREUM_SIM', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='CONFIRMED', max_length=15)),
                ('gas_used', models.BigIntegerField(default=0)),
                ('data_hash', models.CharField(max_length=64)),
                ('anchored_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_events.event')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_txs', to='tap_evidence.evidence')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_blockchain_txs',
                'ordering': ['-anchored_at'],
            },
        ),
    ]
