# Generated by Django 4.2.7 on 2026-04-22 07:53

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tap_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('AUTH', 'Authentication'), ('EVIDENCE', 'Evidence'), ('ADMIN', 'Admin'), ('PROFILE', 'Profile'), ('REPORT', 'Report'), ('BLOCKCHAIN', 'Blockchain'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_image_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('auto', 'Auto')], default='dark', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFY', 'Email Verify')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_otp_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
