# Generated by Django 6.0.4 on 2026-04-25 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('BLOCKCHAIN_NODE', 'Blockchain Node'), ('IPFS_NODE', 'IPFS Node'), ('AI_CLUSTER', 'AI Inference Cluster'), ('DATABASE', 'Database Node'), ('API_GATEWAY', 'API Gateway'), ('EVIDENCE_STORE', 'Evidence Store'), ('FORENSIC_NODE', 'Forensic Network Node')], max_length=25)),
                ('component_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('CRITICAL', 'Critical'), ('HEALING', 'Self-Healing'), ('OFFLINE', 'Offline'), ('RECOVERED', 'Recovered')], default='HEALTHY', max_length=10)),
                ('health_score', models.FloatField(default=100.0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('uptime_percent', models.FloatField(default=100.0)),
                ('auto_healed', models.BooleanField(default=False)),
                ('heal_actions', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'tap_infra_health',
                'ordering': ['health_score'],
            },
        ),
        migrations.CreateModel(
            name='HealingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('REROUTE', 'Evidence Rerouted'), ('RESTORE', 'Storage Restored'), ('FAILOVER', 'Chain Failover'), ('REPIN', 'IPFS Re-pinned'), ('REINDEX', 'Index Rebuilt'), ('BRIDGE', 'Cross-Chain Bridge'), ('BACKUP_NODE', 'Backup Node Activated'), ('CONSENSUS', 'Consensus Repair')], max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('evidence_affected', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('auto_triggered', models.BooleanField(default=True)),
                ('recovery_time_seconds', models.IntegerField(default=0)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tap_heal.infrastructurehealth')),
            ],
            options={
                'db_table': 'tap_healing_events',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
