# Generated by Django 6.0.4 on 2026-04-25 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_evidence', '0002_evidence_is_latest_version_evidence_parent_evidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('algorithm', models.CharField(choices=[('CRYSTALS_DILITHIUM', 'CRYSTALS-Dilithium'), ('CRYSTALS_KYBER', 'CRYSTALS-Kyber'), ('FALCON', 'FALCON'), ('SPHINCS', 'SPHINCS+'), ('XMSS', 'XMSS'), ('PICNIC', 'Picnic')], default='CRYSTALS_DILITHIUM', max_length=30)),
                ('security_level', models.IntegerField(choices=[(1, 'NIST Level 1 (128-bit)'), (2, 'NIST Level 2'), (3, 'NIST Level 3 (192-bit)'), (5, 'NIST Level 5 (256-bit)')], default=3)),
                ('public_key_hash', models.CharField(max_length=64)),
                ('signature_hash', models.CharField(max_length=64)),
                ('lattice_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('quantum_threat_resistant', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantum_sigs', to='tap_evidence.evidence')),
            ],
            options={
                'db_table': 'tap_quantum_sigs',
                'ordering': ['-created_at'],
            },
        ),
    ]
