# Generated by Django 6.0.4 on 2026-04-25 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInvestigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_type', models.CharField(choices=[('TIMELINE_ANOMALY', 'Timeline Anomaly'), ('ATTACKER_PATTERN', 'Attacker Pattern'), ('INSIDER_THREAT', 'Insider Threat'), ('COORDINATED_ATTACK', 'Coordinated Attack'), ('DATA_EXFIL', 'Data Exfiltration'), ('SUPPLY_CHAIN', 'Supply Chain Attack'), ('RANSOMWARE', 'Ransomware Campaign'), ('APT', 'Advanced Persistent Threat')], max_length=25)),
                ('status', models.CharField(choices=[('INITIALIZING', 'Initializing'), ('ANALYZING', 'Analyzing'), ('GENERATING', 'Generating Report'), ('COMPLETE', 'Complete'), ('ESCALATED', 'Escalated to Human'), ('ARCHIVED', 'Archived')], default='INITIALIZING', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('triggered_by', models.CharField(default='AUTO', max_length=50)),
                ('evidence_scope', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('threat_level', models.CharField(default='UNKNOWN', max_length=15)),
                ('narrative', models.TextField(blank=True)),
                ('attacker_profile', models.JSONField(default=dict)),
                ('attack_timeline', models.JSONField(default=list)),
                ('recommended_actions', models.JSONField(default=list)),
                ('legal_citations', models.JSONField(default=list)),
                ('ioc_list', models.JSONField(default=list)),
                ('graph_data', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_org.organization')),
                ('triggered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_ai_investigations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ForensicNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_type', models.CharField(choices=[('INVESTIGATION', 'Investigation Summary'), ('LEGAL', 'Legal Report'), ('INCIDENT', 'Incident Report'), ('EXECUTIVE', 'Executive Brief'), ('COURT', 'Court-Ready Document'), ('INSURANCE', 'Insurance Claim')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('word_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(default='tapdev-llm-v5', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('jurisdictions', models.JSONField(default=list)),
                ('is_translated', models.BooleanField(default=False)),
                ('source_language', models.CharField(blank=True, max_length=10)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narratives', to='tap_autoai.aiinvestigation')),
            ],
            options={
                'db_table': 'tap_forensic_narratives',
                'ordering': ['-generated_at'],
            },
        ),
    ]
