# Generated by Django 6.0.4 on 2026-04-23 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_ai', '0001_initial'),
        ('tap_evidence', '0002_evidence_is_latest_version_evidence_parent_evidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('TIMESTAMP_TAMPER', 'Timestamp Tampering'), ('LOG_DELETION', 'Log Deletion Attack'), ('REPLAY_ATTACK', 'Event Replay Attack'), ('FORGED_UPLOAD', 'Forged Upload Injection'), ('DUPLICATE_EVENTS', 'Duplicate Event Injection'), ('DELAYED_VERIFY', 'Delayed Verification'), ('HASH_COLLISION', 'Hash Collision Attempt'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation'), ('CHAIN_TRUNCATION', 'Chain Truncation'), ('METADATA_FORGE', 'Metadata Forgery')], max_length=30)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DETECTED', 'Detected by AI'), ('EVADED', 'Evaded Detection'), ('ERROR', 'Error')], default='PENDING', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict)),
                ('ai_detected', models.BooleanField(null=True)),
                ('ai_confidence', models.FloatField(null=True)),
                ('events_injected', models.IntegerField(default=0)),
                ('artifacts', models.JSONField(default=list)),
                ('log_output', models.TextField(blank=True)),
                ('ai_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_ai.aiprediction')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='tap_evidence.evidence')),
            ],
            options={
                'db_table': 'tap_attack_sims',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
