# Generated by Django 6.0.4 on 2026-04-24 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('incident_count', models.IntegerField(default=1)),
                ('known_ips', models.JSONField(default=list)),
                ('known_patterns', models.JSONField(default=list)),
                ('risk_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_org.organization')),
            ],
            options={
                'db_table': 'tap_attacker_profiles',
            },
        ),
        migrations.CreateModel(
            name='ThreatPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('INSIDER_THREAT', 'Insider Threat'), ('REPLAY_CAMPAIGN', 'Replay Attack Campaign'), ('TIMESTAMP_FRAUD', 'Timestamp Fraud Pattern'), ('MASS_FORGE', 'Mass Document Forgery'), ('COORDINATED_ATTACK', 'Coordinated Multi-User Attack'), ('AI_EVASION', 'AI Evasion Attempt'), ('DATA_EXFIL', 'Data Exfiltration Signal'), ('PRIVILEGE_ABUSE', 'Privilege Abuse')], max_length=30)),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('probability', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_window_hours', models.IntegerField(default=24)),
                ('evidence_refs', models.JSONField(default=list)),
                ('indicators', models.JSONField(default=list)),
                ('mitigations', models.JSONField(default=list)),
                ('is_confirmed', models.BooleanField(null=True)),
                ('model_version', models.CharField(default='threat-intel-v1', max_length=50)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_org.organization')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threat_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_threat_predictions',
                'ordering': ['-predicted_at'],
            },
        ),
    ]
