# Generated by Django 6.0.4 on 2026-04-25 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_autoai', '0001_initial'),
        ('tap_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('COURT_REPORT', 'Court-Ready Report'), ('INCIDENT_REPORT', 'Incident Report'), ('INSURANCE_CLAIM', 'Insurance Claim'), ('COMPLIANCE_CERT', 'Compliance Certificate'), ('LEGAL_BRIEF', 'Legal Brief'), ('CHAIN_OF_CUSTODY', 'Chain of Custody'), ('EXPERT_TESTIMONY', 'Expert Testimony'), ('GDPR_BREACH', 'GDPR Breach Notification')], max_length=25)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('FILED', 'Filed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('jurisdiction', models.CharField(choices=[('US', 'United States'), ('EU', 'European Union'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('IN', 'India'), ('SG', 'Singapore'), ('INTL', 'International')], default='INTL', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('evidence_refs', models.JSONField(default=list)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('ai_model_used', models.CharField(default='tapdev-legal-ai-v5', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('legal_citations', models.JSONField(default=list)),
                ('blockchain_proof', models.CharField(blank=True, max_length=100)),
                ('word_count', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=1)),
                ('digital_signature', models.CharField(blank=True, max_length=128)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_docs', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_autoai.aiinvestigation')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_org.organization')),
            ],
            options={
                'db_table': 'tap_legal_documents',
                'ordering': ['-generated_at'],
            },
        ),
    ]
