# Generated by Django 6.0.4 on 2026-04-24 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('INITIALIZING', 'Initializing'), ('AGGREGATING', 'Aggregating'), ('STABLE', 'Stable'), ('OUTDATED', 'Outdated')], default='STABLE', max_length=20)),
                ('global_accuracy', models.FloatField(default=0.0)),
                ('global_f1', models.FloatField(default=0.0)),
                ('participating_orgs', models.IntegerField(default=0)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_aggregated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tap_fed_models',
            },
        ),
        migrations.CreateModel(
            name='FederatedUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('local_accuracy', models.FloatField()),
                ('local_f1', models.FloatField()),
                ('samples_trained', models.IntegerField()),
                ('update_hash', models.CharField(max_length=64)),
                ('encrypted_payload', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('AGGREGATED', 'Aggregated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('dp_epsilon', models.FloatField(default=1.0)),
                ('federated_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tap_fed.federatedmodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tap_org.organization')),
            ],
            options={
                'db_table': 'tap_fed_updates',
            },
        ),
    ]
