# Generated by Django 6.0.4 on 2026-04-25 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalThreatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('threat_type', models.CharField(choices=[('ATTACK', 'Cyberattack'), ('BREACH', 'Data Breach'), ('RANSOMWARE', 'Ransomware'), ('APT', 'APT Activity'), ('INSIDER', 'Insider Threat'), ('FRAUD', 'Document Fraud'), ('IOT', 'IoT Attack'), ('CRITICAL_INFRA', 'Critical Infrastructure')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(default='MEDIUM', max_length=10)),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('geo_lat', models.FloatField()),
                ('geo_lon', models.FloatField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='TAP-DEV', max_length=50)),
                ('affected_sectors', models.JSONField(default=list)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tap_global_threats',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('translated_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(default='tapdev-translate-v5', max_length=50)),
                ('evidence_ref', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tap_translations',
                'ordering': ['-created_at'],
            },
        ),
    ]
