# Generated by Django 6.0.4 on 2026-04-23 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tap_evidence', '0002_evidence_is_latest_version_evidence_parent_evidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('BILSTM', 'BiLSTM Sequence Model'), ('CNN_BILSTM', 'CNN+BiLSTM Ensemble'), ('RF_HYBRID', 'Random Forest Hybrid'), ('ISOLATION', 'Isolation Forest')], max_length=20)),
                ('version_tag', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('FAILED', 'Failed')], default='TRAINING', max_length=15)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('auc_roc', models.FloatField(default=0.0)),
                ('confusion_matrix', models.JSONField(default=dict)),
                ('feature_importances', models.JSONField(default=dict)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_ai_models',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_probability', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical')], default='SAFE', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('feature_vector', models.JSONField(default=dict)),
                ('explanation', models.JSONField(default=list)),
                ('detected_patterns', models.JSONField(default=list)),
                ('rule_based_severity', models.CharField(blank=True, max_length=10)),
                ('hybrid_score', models.FloatField(default=0.0)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='tap_evidence.evidence')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_ai.aimodelversion')),
            ],
            options={
                'db_table': 'tap_ai_predictions',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('samples_used', models.IntegerField(default=0)),
                ('epochs', models.IntegerField(default=0)),
                ('log_output', models.TextField(blank=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('model_produced', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tap_ai.aimodelversion')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_ai_training_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
