# Generated by Django 6.0.4 on 2026-04-24 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('org_type', models.CharField(choices=[('LAW_FIRM', 'Law Firm'), ('ENTERPRISE', 'Enterprise'), ('CYBERSEC', 'Cybersecurity'), ('FORENSIC_LAB', 'Forensic Lab'), ('HOSPITAL', 'Hospital'), ('GOVERNMENT', 'Government'), ('INSURANCE', 'Insurance'), ('BANK', 'Bank'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='ENTERPRISE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TRIAL', 'Trial'), ('PENDING', 'Pending')], default='TRIAL', max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_users', models.IntegerField(default=10)),
                ('max_evidence_gb', models.FloatField(default=5.0)),
                ('api_quota_daily', models.IntegerField(default=1000)),
                ('org_settings', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(max_length=8)),
                ('key_hash', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('ADMIN', 'Admin'), ('IOT', 'IoT'), ('MOBILE', 'Mobile')], default='READ', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('requests_count', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tap_org.organization')),
            ],
            options={
                'db_table': 'tap_api_keys',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ORG_ADMIN', 'Org Admin'), ('ANALYST', 'Analyst'), ('INVESTIGATOR', 'Investigator'), ('AUDITOR', 'Auditor'), ('LEGAL_REVIEWER', 'Legal Reviewer'), ('SUBMITTER', 'Submitter')], default='SUBMITTER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('extra_perms', models.JSONField(default=list)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tap_org.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tap_org_memberships',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
